default:
  image: node:16.14.2-alpine

stages:
  - setup
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

install-dependencies:
  stage: setup
  script:
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules

# mozilla requires a zip of the source code to be given for projects that use bundlers like rollup
zip-source:
  stage: setup
  script:
    - apk update
    - apk add --upgrade zip
    - zip -r source.zip . -x *.git* *.idea
  artifacts:
    expire_in: 1 day
    paths:
      - source.zip

release-chrome-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/chrome.zip
    expire_in: 1 week

release-firefox-job:
  stage: release
  script:
    - npm run build-firefox
  artifacts:
    paths:
      - dist/firefox.zip
    expire_in: 1 week
