default:
  image: node:16-alpine

stages:
  - setup
  - release

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

install-dependencies:
  stage: setup
  script:
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 1h
    paths:
      - node_modules

release-chrome-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/chrome
    expire_in: 1 week

release-firefox-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/firefox
    expire_in: 1 week
