default:
  image: node:16-alpine

stages:
  - build
  - release

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 5 minutes

release-chrome-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/chrome
    expire_in: 1 week

release-firefox-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/firefox
    expire_in: 1 week
