default:
  image: node:16-alpine

stages:
  - build
  - release

build-job:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key: NPM_DOWNLOAD_CACHE
    paths:
      - .npm/
  artifacts: 
    paths:
      - 'node_modules'
    expire_in: 30 minutes

release-chrome-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/chrome
    expire_in: 1 week

release-firefox-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/firefox
    expire_in: 1 week
