default:
  image: node:16-alpine

stages:
  - build
  - release

build-job:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - 'node_modules'

release-chrome-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/chrome
    expire_in: 1 week

release-firefox-job:
  stage: release
  script:
    - npm run build-chrome
  artifacts:
    paths:
      - dist/firefox
    expire_in: 1 week
